name: ReplayMenu
version: '${project.version}'
main: re.imc.replaymenu.ReplayMenu
softdepend:
  - ReplaySystem
  - helper
depend:
  - XReplayExtendAPI
commands:
  replaygui:
    permission: "replay.gui"